from imports.finiteautomaton import *

g = Grammar()
g.addProduction('Expr', ['Term'])
g.addProduction('Expr', ['Expr', 'AddOp', 'Term'])
g.addProduction('Expr', ['AddOp', 'Term'])
g.addProduction('Term', ['Factor'])
g.addProduction('Term', ['Term', 'MulOp', 'Factor'])
g.addProduction('Factor', ['Primary'])
g.addProduction('Factor', ['Factor', '^', 'Primary'])
g.addProduction('Factor', ['Factor', '^', 'Primary'])
g.addProduction('Primary', ['number'])
g.addProduction('Primary', ['variable'])
g.addProduction('Primary', ['(', 'Expr', ')'])
g.addProduction('AddOp', ['+'])
g.addProduction('AddOp', ['-'])
g.addProduction('MulOp', ['*'])
g.addProduction('MulOp', ['/'])
g.setInitial('Expr')
g.printGrammar()
g.convert_chomsky_normal_form()
g.printGrammar()

g1 = Grammar()
g1.addProduction('S', ['A', 'b', 'B'])
g1.addProduction('S', ['C'])
g1.addProduction('B', ['A', 'A'])
g1.addProduction('B', ['A', 'C'])
g1.addProduction('C', ['b'])
g1.addProduction('C', ['c'])
g1.addProduction('A', ['a'])
g1.addProduction('A', ['&'])
g1.setInitial('S')
g1.printGrammar()
g1.convert_chomsky_normal_form()
g1.printGrammar()