from imports.finiteautomaton import *

g6 = Grammar()
g6.addProduction('S', ['a', 'S', 'B'])
g6.addProduction('S', ['a', 'S', 'A'])
g6.addProduction('A', ['a'])
g6.addProduction('B', ['b'])
g6.printGrammar()
g6.factorization_direct()
g6.printGrammar()

g7 = Grammar()
g7.addProduction('S', ['A', 'B'])
g7.addProduction('S', ['B', 'C'])
g7.addProduction('A', ['a', 'D'])
g7.addProduction('A', ['c', 'C'])
g7.addProduction('B', ['a', 'B'])
g7.addProduction('B', ['d', 'D'])
g7.addProduction('C', ['e', 'C'])
g7.addProduction('C', ['e', 'A'])
g7.addProduction('D', ['f', 'D'])
g7.addProduction('D', ['C', 'B'])
g7.printGrammar()
g7.factorization_indirect()
g7.printGrammar()