from imports.finiteautomaton import *

g2 = Grammar()
g2.addProduction('S', ['S', 'a'])
g2.addProduction('S', ['b'])
g2.printGrammar()
g2.remove_left_recursion_direct()
g2.printGrammar()

g3 = Grammar()
g3.addProduction('E', ['E', '+', 'T'])
g3.addProduction('E', ['T'])
g3.addProduction('T', ['T', '*', 'F'])
g3.addProduction('T', ['F'])
g3.addProduction('F', ['(', 'E', ')'])
g3.addProduction('F', ['id'])
g3.printGrammar()
g3.remove_left_recursion_direct()
g3.printGrammar()

g4 = Grammar()
g4.addProduction('S', ['A', 'a'])
g4.addProduction('S', ['b'])
g4.addProduction('A', ['A', 'c'])
g4.addProduction('A', ['S', 'd'])
g4.addProduction('A', ['a'])
g4.printGrammar()
g4.remove_left_recursion_indirect()
g4.printGrammar()

g5 = Grammar()
g5.addProduction('S', ['A', 'a'])
g5.addProduction('S', ['S', 'b'])
g5.addProduction('A', ['S', 'c'])
g5.addProduction('A', ['d'])
g5.printGrammar()
g5.remove_left_recursion_direct()
g5.printGrammar()
g5.remove_left_recursion_indirect()
g5.printGrammar()