from imports.finiteautomaton import *

g8 = Grammar()
g8.addProduction('S', ['A', 'b'])
g8.addProduction('S', ['A', 'B', 'c'])
g8.addProduction('B', ['b', 'B'])
g8.addProduction('B', ['A', 'd'])
g8.addProduction('B', ['&'])
g8.addProduction('A', ['a', 'A'])
g8.addProduction('A', ['&'])
g8.setInitial('S')
g8.printGrammar()
print(g8.first('S'))
print(g8.first('A'))
print(g8.first('B'))
print()

g9 = Grammar()
g9.addProduction('S', ['A', 'B', 'C'])
g9.addProduction('A', ['a', 'A'])
g9.addProduction('A', ['&'])
g9.addProduction('B', ['b', 'B'])
g9.addProduction('B', ['A', 'C', 'd'])
g9.addProduction('C', ['c', 'C'])
g9.addProduction('C', ['&'])
g9.setInitial('S')
g9.printGrammar()
print(g9.first('S'))
print(g9.first('A'))
print(g9.first('B'))
print(g9.first('C'))